# Generated by Django 3.2.5 on 2021-12-13 17:14

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile No.')),
                ('from_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='From Email')),
                ('to_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='To Email')),
                ('email_subject', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject')),
                ('resume', models.FileField(blank=True, null=True, upload_to=apis.models.resume_dir, verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Candidate Details',
                'verbose_name_plural': 'Candidate Details',
                'db_table': 'mr_condidates_details',
            },
        ),
    ]
