# Generated by Django 3.2.5 on 2022-01-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_candidatedetails_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='candidatedetails',
            name='email_subject',
            field=models.TextField(blank=True, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='candidatedetails',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
